version: "3.8"
name: spring-jdk-21-env

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10003:10003"
    deploy:
      resources:
        limits:
          cpus: 2.0
          memory: 4GB
        reservations:
          cpus: 2.0
          memory: 4GB
